#!/usr/bin/env bash
# scripts/upload-media.sh
#
# One-time media upload to Vercel Blob.
# Run from project root after:
#   1. npx vercel@latest blob store add brusnika-media
#   2. npx vercel@latest env pull .env.local
#
# Requires: BLOB_READ_WRITE_TOKEN in environment (pulled via env pull above)
# Requires: ffmpeg available at /opt/homebrew/bin/ffmpeg (for poster extraction)
#
# Uploads all 9 audio + all 9 video + 4 poster JPEGs for displayed clips.
# Appends each CDN URL mapping to .planning/phases/02-media-islands/MEDIA-URLS.md
#
# Source: https://vercel.com/docs/vercel-blob/manage-blob-storage (VERIFIED: official docs)

set -euo pipefail

FFMPEG=/opt/homebrew/bin/ffmpeg
MEDIA_URLS=".planning/phases/02-media-islands/MEDIA-URLS.md"
POSTERS_DIR="posters"

# Ensure the MEDIA-URLS.md file exists and has a header
if [ ! -f "$MEDIA_URLS" ]; then
  mkdir -p "$(dirname "$MEDIA_URLS")"
  cat > "$MEDIA_URLS" <<'EOF'
# Media CDN URLs

Generated by scripts/upload-media.sh
All URLs: https://<store-id>.public.blob.vercel-storage.com/<pathname>

## Audio

| Local file | Pathname | CDN URL |
|-----------|----------|---------|
EOF
fi

# Helper: upload one file, print and record URL
upload() {
  local LOCAL="$1"
  local PATHNAME="$2"
  local SECTION="$3"

  echo ""
  echo ">>> Uploading: $LOCAL → $PATHNAME"

  URL=$(npx vercel@latest blob put "$LOCAL" \
    --pathname "$PATHNAME" \
    --access public \
    --allow-overwrite \
    2>&1 | grep -E 'https://' | tail -1)

  if [ -z "$URL" ]; then
    echo "ERROR: No URL returned for $LOCAL. Check BLOB_READ_WRITE_TOKEN and Blob store."
    exit 1
  fi

  echo "    CDN URL: $URL"

  # Append to MEDIA-URLS.md
  printf "| \`%s\` | \`%s\` | %s |\n" "$LOCAL" "$PATHNAME" "$URL" >> "$MEDIA_URLS"
}

# ---------------------------------------------------------------------------
# 1. Extract poster frames for the 4 displayed clips (ffmpeg)
# ---------------------------------------------------------------------------

echo ""
echo "=== Step 1: Extract poster frames for 4 displayed clips ==="

mkdir -p "$POSTERS_DIR"

POSTER_CLIPS=(
  "video/Доодури.MP4:doorudi"
  "video/Кажется.MP4:kazhetsya"
  "video/Клуб Неоправданных Надежд.mp4:klub"
  "video/Занавес.MP4:zanaves"
)

for entry in "${POSTER_CLIPS[@]}"; do
  VIDEO_FILE="${entry%%:*}"
  SLUG="${entry##*:}"
  POSTER_OUT="$POSTERS_DIR/${SLUG}-poster.jpg"

  if [ -f "$POSTER_OUT" ]; then
    echo "  [skip] $POSTER_OUT already exists"
  else
    echo "  Extracting: $VIDEO_FILE → $POSTER_OUT"
    "$FFMPEG" -i "$VIDEO_FILE" -ss 00:00:03 -vframes 1 -q:v 2 "$POSTER_OUT" -y 2>/dev/null
    echo "  Done: $POSTER_OUT"
  fi
done

# ---------------------------------------------------------------------------
# 2. Upload all 9 audio files (ALL uploaded per D-03, even non-displayed)
# ---------------------------------------------------------------------------

echo ""
echo "=== Step 2: Upload audio files (9 total) ==="
printf "\n## Audio\n\n| Local file | Pathname | CDN URL |\n|-----------|----------|--------|\n" >> "$MEDIA_URLS"

upload "music/Доодури.mp3"                     "audio/doorudi.mp3"            "audio"
upload "music/Кажется.mp3"                     "audio/kazhetsya.mp3"          "audio"
upload "music/Клуб Неоправданных Надежд.mp3"   "audio/klub.mp3"               "audio"
upload "music/Занавес.mp3"                     "audio/zanaves.mp3"            "audio"
upload "music/Игрок.mp3"                       "audio/igrok.mp3"              "audio"
upload "music/Безнаказанным.mp3"               "audio/beznakazannym.mp3"      "audio"
upload "music/Ива.mp3"                         "audio/iva.mp3"                "audio"
upload "music/Завтра была зима.mp3"            "audio/zavtra.mp3"             "audio"
upload "music/Кажется акустика.mp3"            "audio/kazhetsya-akustika.mp3" "audio"

# ---------------------------------------------------------------------------
# 3. Upload all 9 video files
# ---------------------------------------------------------------------------

echo ""
echo "=== Step 3: Upload video files (9 total) ==="
printf "\n## Video\n\n| Local file | Pathname | CDN URL |\n|-----------|----------|--------|\n" >> "$MEDIA_URLS"

upload "video/Доодури.MP4"                     "video/doorudi.mp4"            "video"
upload "video/Кажется.MP4"                     "video/kazhetsya.mp4"          "video"
upload "video/Клуб Неоправданных Надежд.mp4"   "video/klub.mp4"               "video"
upload "video/Занавес.MP4"                     "video/zanaves.mp4"            "video"
upload "video/Игрок.MP4"                       "video/igrok.mp4"              "video"
upload "video/Безнаказанным.MP4"               "video/beznakazannym.mp4"      "video"
upload "video/Ива.MP4"                         "video/iva.mp4"                "video"
upload "video/Завтра была зима.mp4"            "video/zavtra.mp4"             "video"
upload "video/Кажется акустика.MP4"            "video/kazhetsya-akustika.mp4" "video"

# ---------------------------------------------------------------------------
# 4. Upload 4 poster JPEGs
# ---------------------------------------------------------------------------

echo ""
echo "=== Step 4: Upload poster JPEGs (4 displayed clips) ==="
printf "\n## Posters\n\n| Local file | Pathname | CDN URL |\n|-----------|----------|--------|\n" >> "$MEDIA_URLS"

upload "$POSTERS_DIR/doorudi-poster.jpg"   "posters/doorudi-poster.jpg"   "poster"
upload "$POSTERS_DIR/kazhetsya-poster.jpg" "posters/kazhetsya-poster.jpg" "poster"
upload "$POSTERS_DIR/klub-poster.jpg"      "posters/klub-poster.jpg"      "poster"
upload "$POSTERS_DIR/zanaves-poster.jpg"   "posters/zanaves-poster.jpg"   "poster"

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------

echo ""
echo "=== All uploads complete! ==="
echo ""
echo "CDN URL map written to: $MEDIA_URLS"
echo ""
echo "Spot-check one audio URL for iOS seek support (expect HTTP 206 + accept-ranges):"
echo "  Pick an audioUrl from $MEDIA_URLS and run:"
echo '  curl -sI -H "Range: bytes=0-1023" "<CDN_URL>" | grep -iE "HTTP/|accept-ranges|content-range"'
